export const LOCAL_STORAGE_DB_KEY = 'rco-'
export const DATE_FORMAT = 'DD-MM-YYYY'
export const DATETIME_FORMAT = 'DD-MM-YYYY HH =mm =ss'
export const TOKEN_KEY = 'rco-user'
export const SALT = 'salt'
// major table/resource names
export const R_USERS = 'users'
export const R_BATCHES = 'batches'
export const R_PROJECTS = 'projects'
export const R_PLATFORMS = 'platforms'
export const R_ITEMS = 'items'
export const R_AUDIT = 'audit'
export const R_VAULT_LOCATION = 'vaultLocation'
export const R_ORGANISATION = 'organisation'
