name: Playwright E2E

on:
  push:
    branches: [e2e_login_test]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn

      - name: Install playwright dependencies
        run: npx playwright Install
      
      - name: Execute playwright tests
        run: yarn e2e
